# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

dist <- function(x) {
    .Call(`_MSLSMediaBiasR_dist`, x)
}

mean_mat <- function(A) {
    .Call(`_MSLSMediaBiasR_mean_mat`, A)
}

median_mat <- function(A) {
    .Call(`_MSLSMediaBiasR_median_mat`, A)
}

sd_mat <- function(A) {
    .Call(`_MSLSMediaBiasR_sd_mat`, A)
}

mvrnormArma <- function(n, mu, sigma) {
    .Call(`_MSLSMediaBiasR_mvrnormArma`, n, mu, sigma)
}

clog_sum_exp <- function(x) {
    .Call(`_MSLSMediaBiasR_clog_sum_exp`, x)
}

csoftmax <- function(x) {
    .Call(`_MSLSMediaBiasR_csoftmax`, x)
}

logistic_d <- function(x) {
    .Call(`_MSLSMediaBiasR_logistic_d`, x)
}

arma_sort <- function(x, y, z) {
    .Call(`_MSLSMediaBiasR_arma_sort`, x, y, z)
}

logbivnorm <- function(x, mean, sigma) {
    .Call(`_MSLSMediaBiasR_logbivnorm`, x, mean, sigma)
}

FFBS <- function(Acc, Bcc, alef, bet, Eta, P, T) {
    .Call(`_MSLSMediaBiasR_FFBS`, Acc, Bcc, alef, bet, Eta, P, T)
}

gammaSamplingEn <- function(leaning, zi_1, phi, gamma_0, gamma_1, a_gamma_0, a_gamma_1, b_gamma_0, b_gamma_1, interp_eq, prop_sigma) {
    .Call(`_MSLSMediaBiasR_gammaSamplingEn`, leaning, zi_1, phi, gamma_0, gamma_1, a_gamma_0, a_gamma_1, b_gamma_0, b_gamma_1, interp_eq, prop_sigma)
}

phiSamplingEn <- function(leaning, zi_1, phi, gamma_0, gamma_1, a_phi, b_phi, interp_eq, prop_sigma) {
    .Call(`_MSLSMediaBiasR_phiSamplingEn`, leaning, zi_1, phi, gamma_0, gamma_1, a_phi, b_phi, interp_eq, prop_sigma)
}

cseq <- function(first, last, by) {
    .Call(`_MSLSMediaBiasR_cseq`, first, last, by)
}

dmvnrm_arma <- function(x, mean, sigma, logd = FALSE) {
    .Call(`_MSLSMediaBiasR_dmvnrm_arma`, x, mean, sigma, logd)
}

dmvnrm_arma_fast <- function(x, mean, sigma, logd = FALSE) {
    .Call(`_MSLSMediaBiasR_dmvnrm_arma_fast`, x, mean, sigma, logd)
}

cdiff <- function(A) {
    .Call(`_MSLSMediaBiasR_cdiff`, A)
}

ecldist_point <- function(A, B, i) {
    .Call(`_MSLSMediaBiasR_ecldist_point`, A, B, i)
}

ecldist <- function(A, B) {
    .Call(`_MSLSMediaBiasR_ecldist`, A, B)
}

ecldistp2 <- function(A, B) {
    .Call(`_MSLSMediaBiasR_ecldistp2`, A, B)
}

gath <- function(A) {
    .Call(`_MSLSMediaBiasR_gath`, A)
}

gath_tri <- function(A) {
    .Call(`_MSLSMediaBiasR_gath_tri`, A)
}

caggH <- function(ab_logl, ab_logl_prop, pois, pois_prop, N) {
    .Call(`_MSLSMediaBiasR_caggH`, ab_logl, ab_logl_prop, pois, pois_prop, N)
}

caggG <- function(pois, pois_prop, N) {
    .Call(`_MSLSMediaBiasR_caggG`, pois, pois_prop, N)
}

cagglogG <- function(g_a, g_b, M, Times) {
    .Call(`_MSLSMediaBiasR_cagglogG`, g_a, g_b, M, Times)
}

cagglogH <- function(B_a, B_b, N, Times) {
    .Call(`_MSLSMediaBiasR_cagglogH`, B_a, B_b, N, Times)
}

ziPropSampling <- function(zi, lambda, N) {
    .Call(`_MSLSMediaBiasR_ziPropSampling`, zi, lambda, N)
}

procrustes_cpp <- function(X, Y) {
    .Call(`_MSLSMediaBiasR_procrustes_cpp`, X, Y)
}

rdirichlet_cpp <- function(num_samples, alpha_m) {
    .Call(`_MSLSMediaBiasR_rdirichlet_cpp`, num_samples, alpha_m)
}

sampleTransP <- function(xi_state1, xi_state2, omega_lower_a, omega_lower_b, P, Time) {
    .Call(`_MSLSMediaBiasR_sampleTransP`, xi_state1, xi_state2, omega_lower_a, omega_lower_b, P, Time)
}

vec_nbet <- function(x, N) {
    .Call(`_MSLSMediaBiasR_vec_nbet`, x, N)
}

ZetaSamplingAdC <- function(zi_s_1, zi_s_2, lam_ad_zs, mu_mat_zs, Sigma_ad_zs, alpha, beta, xi_state_s, x_i, DBplane_i, x_w, leaning, x_ones, mu_s, sigma_s, gamma_0, gamma_1, phi, M, N, acc_star, interp_eq, ite) {
    .Call(`_MSLSMediaBiasR_ZetaSamplingAdC`, zi_s_1, zi_s_2, lam_ad_zs, mu_mat_zs, Sigma_ad_zs, alpha, beta, xi_state_s, x_i, DBplane_i, x_w, leaning, x_ones, mu_s, sigma_s, gamma_0, gamma_1, phi, M, N, acc_star, interp_eq, ite)
}

vec_nbet_tri <- function(beta, N) {
    .Call(`_MSLSMediaBiasR_vec_nbet_tri`, beta, N)
}

vec_nbet_tri_a <- function(beta, N) {
    .Call(`_MSLSMediaBiasR_vec_nbet_tri_a`, beta, N)
}

betaSamplingEn <- function(vec_y, beta, vec_dist, beta_a, beta_b, N, Time, x_i, prop_sigma) {
    .Call(`_MSLSMediaBiasR_betaSamplingEn`, vec_y, beta, vec_dist, beta_a, beta_b, N, Time, x_i, prop_sigma)
}

betaSamplingEnAdC <- function(vec_y, lam_ad_beta, mu_mat_beta, Sigma_ad_beta, beta, vec_dist, beta_a, beta_b, N, Time, x_i, acc_star, ite) {
    .Call(`_MSLSMediaBiasR_betaSamplingEnAdC`, vec_y, lam_ad_beta, mu_mat_beta, Sigma_ad_beta, beta, vec_dist, beta_a, beta_b, N, Time, x_i, acc_star, ite)
}

rinvgamma <- function(shape, scale) {
    .Call(`_MSLSMediaBiasR_rinvgamma`, shape, scale)
}

invSamplingEn <- function(zi_s_1, a_prior_ig, b_prior_ig, N) {
    .Call(`_MSLSMediaBiasR_invSamplingEn`, zi_s_1, a_prior_ig, b_prior_ig, N)
}

PosteriorPredictive <- function(beta, zi_a_1, zi_b_1, xi_state1, N, Time) {
    .Call(`_MSLSMediaBiasR_PosteriorPredictive`, beta, zi_a_1, zi_b_1, xi_state1, N, Time)
}

alphaSamplingEn <- function(vec_y, alpha, alpha_a, alpha_b, N, Time, M, prop_sigma) {
    .Call(`_MSLSMediaBiasR_alphaSamplingEn`, vec_y, alpha, alpha_a, alpha_b, N, Time, M, prop_sigma)
}

MCMC <- function(princ_w, princ_ones, x_w, x_ones, leaning, lam_ad_beta, mu_mat_beta, Sigma_ad_beta, lam_ad_za, mu_mat_za, Sigma_ad_za, lam_ad_zb, mu_mat_zb, Sigma_ad_zb, beta, xi_state1, zi_a_1, zi_b_1, mu_beta, sigma_beta, mu_a, sigma_a, mu_b, sigma_b, s_a, s_b, phi, gamma_0, gamma_1, a_phi, b_phi, a_gamma_0, b_gamma_0, a_gamma_1, b_gamma_1, omega_lower_a, omega_lower_b, P, N, Time, x_i, DBplane_i, prop_sd_rg = 0.0025, prop_sd_gamma = 0.00015, prop_sd_phi = 40, acc_beta = 0.25, acc_zeta_a = 0.25, acc_zeta_b = 0.25, pivot = 14, sign = -1, interp_eq = 1, ms_eq = 1, rg_eq = 0, Iterations = 10000L) {
    .Call(`_MSLSMediaBiasR_MCMC`, princ_w, princ_ones, x_w, x_ones, leaning, lam_ad_beta, mu_mat_beta, Sigma_ad_beta, lam_ad_za, mu_mat_za, Sigma_ad_za, lam_ad_zb, mu_mat_zb, Sigma_ad_zb, beta, xi_state1, zi_a_1, zi_b_1, mu_beta, sigma_beta, mu_a, sigma_a, mu_b, sigma_b, s_a, s_b, phi, gamma_0, gamma_1, a_phi, b_phi, a_gamma_0, b_gamma_0, a_gamma_1, b_gamma_1, omega_lower_a, omega_lower_b, P, N, Time, x_i, DBplane_i, prop_sd_rg, prop_sd_gamma, prop_sd_phi, acc_beta, acc_zeta_a, acc_zeta_b, pivot, sign, interp_eq, ms_eq, rg_eq, Iterations)
}

update_zi <- function(zi_a_it, zi_b_it) {
    .Call(`_MSLSMediaBiasR_update_zi`, zi_a_it, zi_b_it)
}

update_x <- function(x_it, zi_a_it, zi_b_it) {
    .Call(`_MSLSMediaBiasR_update_x`, x_it, zi_a_it, zi_b_it)
}

